name: Android CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read  # 只保留读取代码的权限（无需 Pages 权限）

jobs:
  build:
    runs-on: ubuntu-latest  # 去掉 environment 配置（不需要关联 Pages 环境）

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Build with Gradle
      run: |
        echo 'org.gradle.caching=true' >> gradle.properties
        echo 'org.gradle.parallel=true' >> gradle.properties
        echo 'org.gradle.vfs.watch=true' >> gradle.properties
        echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
        ./gradlew publishToMavenLocal  # 生成 AAR/JAR 并发布到本地 Maven
        ./gradlew --stop
      env:
        # 签名配置（不需要可注释）
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.maven_pgp_signingKey }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.maven_pgp_signingPassword }}
    - name: Upload library
      uses: actions/upload-artifact@v4
      with:
        name: library
        path: ~/.m2/repository/
        include-hidden-files: true
        if-no-files-found: error
    # 删除以下两行 Pages 相关步骤
    # - name: Upload pages
    #   uses: actions/upload-pages-artifact@v3
    #   with:
    #     path: 'api/build/intermediates/java_doc_dir/release/javaDocReleaseGeneration'
    # - name: Deploy to GitHub Pages
    #   id: deployment
    #   uses: actions/deploy-pages@v4
